spring:
  data:
    cassandra:
      keyspace-name: testKeySpace
      contact-points:
        - 127.0.0.1:9043
      local-datacenter: datacenter1
      schema-action: CREATE_IF_NOT_EXISTS
#        datastax-java-driver.advanced.connection.warn-on-init-error = false

#basic:
#  load-balancing-policy:
#    local-datacenter: DC1