services:
  redis:
    image: redis:6.2.6
    ports:
      - "127.0.0.1:6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8040:8081"