version: '3.1'

services:
  redis:
    image: redis:6.2.6
    ports:
      - "127.0.0.1:6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "127.0.0.1:8040:8081"
  mongodb:
    image: mongo:6.0.3
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    ports:
      - "127.0.0.1:8041:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:password@mongodb:27017/
  postgres:
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  adminer:
    image: adminer
    ports:
      - "127.0.0.1:8042:8080"

networks:
  back-tier: {}
