version: '3.7'

services:
  minio:                       # rename on different nodes
    hostname: minio            # rename on different nodes
    image: quay.io/minio/minio:RELEASE.2023-07-21T21-12-44Z.fips
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioroot
      MINIO_ROOT_PASSWORD: V3ry_hard
